export const MINESWEEPER_ABI = [
  // ── Events ──────────────────────────────────────────────────
  {
    type: "event",
    name: "GameStarted",
    inputs: [
      { indexed: true,  name: "gameId",     type: "uint256" },
      { indexed: true,  name: "player",     type: "address" },
      { indexed: false, name: "sessionKey", type: "address" },
      { indexed: false, name: "gridSize",   type: "uint8"   },
      { indexed: false, name: "difficulty", type: "uint8"   },
      { indexed: false, name: "entryFee",   type: "uint256" },
      { indexed: false, name: "maxPayout",  type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "FirstFlipMade",
    inputs: [
      { indexed: true,  name: "gameId",       type: "uint256" },
      { indexed: false, name: "tileIndex",    type: "uint8"   },
      { indexed: false, name: "vrfRequestId", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "TileRevealed",
    inputs: [
      { indexed: true,  name: "gameId",        type: "uint256" },
      { indexed: true,  name: "caller",         type: "address" },
      { indexed: false, name: "tileIndex",      type: "uint8"   },
      { indexed: false, name: "isMine",         type: "bool"    },
      { indexed: false, name: "safeRevealed",   type: "uint8"   },
      { indexed: false, name: "currentPayout",  type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "GameCashedOut",
    inputs: [
      { indexed: true,  name: "gameId",       type: "uint256" },
      { indexed: true,  name: "player",       type: "address" },
      { indexed: false, name: "payout",       type: "uint256" },
      { indexed: false, name: "safeRevealed", type: "uint8"   },
      { indexed: false, name: "totalSafe",    type: "uint8"   },
    ],
  },
  {
    type: "event",
    name: "GameOver",
    inputs: [
      { indexed: true,  name: "gameId",      type: "uint256" },
      { indexed: true,  name: "player",      type: "address" },
      { indexed: false, name: "mineTile",    type: "uint8"   },
      { indexed: false, name: "mineBitmask", type: "uint64"  },
    ],
  },
  {
    type: "event",
    name: "PoolDeposited",
    inputs: [
      { indexed: true,  name: "sender", type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "FeeWithdrawn",
    inputs: [
      { indexed: true,  name: "owner",  type: "address" },
      { indexed: false, name: "amount", type: "uint256" },
    ],
  },
  {
    type: "event",
    name: "Withdrawn",
    inputs: [
      { indexed: true,  name: "recipient", type: "address" },
      { indexed: false, name: "amount",    type: "uint256" },
      { indexed: false, name: "percentBps", type: "uint256" },
    ],
  },
  // ── Write Functions ──────────────────────────────────────────
  {
    type: "function",
    name: "startGame",
    stateMutability: "payable",
    inputs: [
      { name: "gridSize",   type: "uint8"   },
      { name: "difficulty", type: "uint8"   },
      { name: "sessionKey", type: "address" },
    ],
    outputs: [{ name: "gameId", type: "uint256" }],
  },
  {
    type: "function",
    name: "firstFlip",
    stateMutability: "nonpayable",
    inputs: [
      { name: "gameId",    type: "uint256" },
      { name: "tileIndex", type: "uint8"   },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "flipTile",
    stateMutability: "nonpayable",
    inputs: [
      { name: "gameId",    type: "uint256" },
      { name: "tileIndex", type: "uint8"   },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "flipTiles",
    stateMutability: "nonpayable",
    inputs: [
      { name: "gameId",      type: "uint256" },
      { name: "tileIndices", type: "uint8[]" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "cashOut",
    stateMutability: "nonpayable",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setSessionKey",
    stateMutability: "nonpayable",
    inputs: [
      { name: "gameId",       type: "uint256" },
      { name: "newSessionKey", type: "address" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelStuckGame",
    stateMutability: "nonpayable",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "depositPool",
    stateMutability: "payable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "withdrawFees",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "percentBps", type: "uint256" },
      { name: "recipient",  type: "address" },
    ],
    outputs: [],
  },
  // ── Admin Functions ──────────────────────────────────────────
  {
    type: "function",
    name: "setGameConfig",
    stateMutability: "nonpayable",
    inputs: [
      { name: "gridSize",      type: "uint8"   },
      { name: "entryFeeWei",   type: "uint256" },
      { name: "maxPayoutBPS",  type: "uint16"  },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setGridActive",
    stateMutability: "nonpayable",
    inputs: [
      { name: "gridSize", type: "uint8" },
      { name: "active",   type: "bool"  },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setMineCount",
    stateMutability: "nonpayable",
    inputs: [
      { name: "gridSize",   type: "uint8" },
      { name: "difficulty", type: "uint8" },
      { name: "mineCount",  type: "uint8" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setPlatformFee",
    stateMutability: "nonpayable",
    inputs: [{ name: "feeBPS", type: "uint16" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setMaxConcurrentGames",
    stateMutability: "nonpayable",
    inputs: [
      { name: "gridSize", type: "uint8"  },
      { name: "max",      type: "uint32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setMinPoolThreshold",
    stateMutability: "nonpayable",
    inputs: [
      { name: "gridSize", type: "uint8"   },
      { name: "amount",   type: "uint256" },
    ],
    outputs: [],
  },
  // ── Read Functions ───────────────────────────────────────────
  {
    type: "function",
    name: "getGame",
    stateMutability: "view",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [
      { name: "player",             type: "address" },
      { name: "sessionKey",         type: "address" },
      { name: "gridSize",           type: "uint8"   },
      { name: "difficulty",         type: "uint8"   },
      { name: "entryFee",           type: "uint256" },
      { name: "maxPayout",          type: "uint256" },
      { name: "mineBitmask",        type: "uint64"  },
      { name: "revealedBitmask",     type: "uint64"  },
      { name: "safeRevealed",       type: "uint8"   },
      { name: "totalSafe",          type: "uint8"   },
      { name: "status",             type: "uint8"   },
      { name: "startBlock",         type: "uint256" },
      { name: "startedAt",          type: "uint256" },
      { name: "endedAt",            type: "uint256" },
      { name: "revealedAdjacency",  type: "uint8[]" },
    ],
  },
  {
    type: "function",
    name: "getCurrentPayout",
    stateMutability: "view",
    inputs: [{ name: "gameId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "isGridAvailable",
    stateMutability: "view",
    inputs: [
      { name: "gridSize",   type: "uint8" },
      { name: "difficulty", type: "uint8" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "getPoolHealth",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "pool",            type: "uint256" },
      { name: "reserved",        type: "uint256" },
      { name: "fees",            type: "uint256" },
      { name: "contractBalance", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "playerActiveGame",
    stateMutability: "view",
    inputs: [{ name: "player", type: "address" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "gridConfigs",
    stateMutability: "view",
    inputs: [{ name: "gridSize", type: "uint8" }],
    outputs: [
      { name: "totalTiles",       type: "uint8"   },
      { name: "entryFee",         type: "uint256" },
      { name: "maxPayoutBPS",     type: "uint16"  },
      { name: "maxConcurrent",    type: "uint32"  },
      { name: "minPoolThreshold", type: "uint256" },
      { name: "active",           type: "bool"    },
    ],
  },
  {
    type: "function",
    name: "mineCounts",
    stateMutability: "view",
    inputs: [
      { name: "gridSize",   type: "uint8" },
      { name: "difficulty", type: "uint8" },
    ],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "platformFeeBPS",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
  },
  {
    type: "function",
    name: "nextGameId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "poolBalance",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
] as const;
